import { useState } from "react";

const lines = [
  "for(const day of life) improve(day);",
  "try { code(); } catch(e) { learn(e); }",
  "let curiosity = Infinity;",
  "function grow(){ return practice + patience; }",
  "npm install confidence",
  "yarn add discipline",
  "sudo make me a developer",
  "chmod +x dreams.sh",
  "ping success.com",
  "refactor(today);",
  "debug(tomorrow);",
  "deploy(whenReady);",
  "git push origin growth",
  "branch('better-version-of-me');",
  "merge(skill, consistency);",
  "rebase(mistakes, lessons);",
  "const focus = true;",
  "let distractions = null;",
  "Promise.resolve(hardWork);",
  "await opportunities;",
  "async function future() {}",
  "return early; // but not in life",
  "break; // bad habits",
  "continue; // learning",
  "map(dreams).filter(effort);",
  "reduce(problems, solutions);",
  "Object.keys(possibilities).length",
  "JSON.stringify(progress)",
  "parseInt(experience)",
  "Boolean(determination)",
  "NaN === NotActuallyNeeded",
  "undefined !== potential",
  "typeof mindset === 'growth'",
  "instanceof Developer",
  "new Date().getFullYear() === grind",
  "setTimeout(success, 5000);",
  "clearInterval(doubt);",
  "window.scrollTo(0, goals);",
  "document.querySelector('#future');",
  "addEventListener('opportunity', act);",
  "removeEventListener('fear', hesitate);",
  "localStorage.setItem('confidence', true);",
  "sessionStorage.setItem('focus', true);",
  "history.push('next-level');",
  "404.sleep.notFound();",
  "CPU: 100% dedication",
  "RAM: loaded with ideas",
  "GPU: rendering dreams",
  "while(true) { practice(); }",
  "exit(comfortZone);",
  "enter(growthZone);",
  "compile(knowledge);",
  "link(effort, success);",
  "import { discipline } from 'daily-routine';",
  "export default perseverance;",
  "class Developer extends Human {}",
  "interface Success { effort: number }",
  "abstract class Limits {}",
  "override excuses();",
  "super.learn();",
  "this.build();",
  "self.improve();",
  "print('stay consistent');",
  "echo 'never quit';",
  "grep -r 'opportunities' ./life",
  "find . -name 'success'",
  "touch skills.txt",
  "cat motivation.log",
  "tail -f progress.log",
  "head -n 1 goals.txt",
  "ps aux | grep growth",
  "kill -9 procrastination",
  "top -u ambition",
  "ssh into future",
  "curl inspiration.dev",
  "wget discipline.tar.gz",
  "tar -xvf potential.tar",
  "zip -r achievements.zip",
  "unzip knowledge.zip",
  "mount mindset",
  "umount fear",
  "docker build character",
  "kubectl apply -f dreams.yaml",
  "helm install success",
  "SELECT passion FROM self;",
  "UPDATE skills SET level='advanced';",
  "DELETE FROM doubts;",
  "INSERT INTO life VALUES('progress');",
  "CREATE TABLE achievements(id INT);",
  "DROP TABLE excuses;",
  "ALTER TABLE mindset ADD grit;",
  "JOIN effort ON consistency;",
  "COMMIT work;",
  "ROLLBACK laziness;"
];


export default function Footer() {
  const [randomLine] = useState(() => {
    return lines[Math.floor(Math.random() * lines.length)];
  });

  return (
    <footer className="mt-24 mb-10 text-center">
      <p className="font-mono text-xs opacity-60 tracking-wider text-gray-400">
        {randomLine}
      </p>
    </footer>
  );
}
